package com.petpicker

import java.util.ArrayList;
  import java.io.BufferedReader;
  import java.io.IOException;
  import java.io.InputStreamReader;

rule "age"
    when
    then
    	Property age = MainWindow.setQuestion("age");
    	insert (new Property(age.getType(), age.getValue()));
end

rule "allergyGeneral"
    when
    then
        Property allergy = MainWindow.setQuestion("allergy");
        insert (new Property(allergy.getType(), allergy.getValue()));
end


rule "allergySpecificI"
	when
		Property(type=="allergy" && value=="tak")
	then
		MainWindow.setQuestion("allergyType");
end

rule "family"
    when
    then
    	MainWindow.setQuestion("family");
end

rule "childSubstitute"
	salience 4
    when
		Property(type=="family" && value=="nie")
    then
    	MainWindow.setQuestion("childSubstitute");
end

rule "allergySpecificII"
	when
		Property(type=="familyAllergy" && value=="tak")
	then
		MainWindow.setQuestion("allergySpecificII");
end

rule "familyAllergy"
    when
		Property(type=="family" && value=="tak")
		Property(type=="furPossible" && value == "tak")
    then
    	MainWindow.setQuestion("familyAllergy");
end

rule "children"
    when
		(or Property(type=="family" && value=="tak")
			Property(type=="familyAllergyType"))
    then
    	MainWindow.setQuestion( "children");
end

rule "childrenAge"
    when
		Property(type=="children" && value=="tak")
    then
    	MainWindow.setQuestion("childrenAge");
end

/*

rule "timeRequirements"
	salience 20
    when
		Pet(timeRequirements=="undefined")
    then
    	MainWindow.setQuestion("timeRequirements");

end



rule "timeAtHome"
	salience 4
    when
		Person(family=="nie" && timeAtHome=="undefined")
    then
    	MainWindow.setQuestion("timeAtHome");
end



rule "children"
	salience 6
    when
		Person(family=="tak" && children=="undefined")
    then
    	MainWindow.setQuestion( "children");
end

rule "childrenAge"
	salience 6
    when
		Person(children=="tak" && childrenAge=="undefined")
    then
    	MainWindow.setQuestion("childrenAge");
end

rule "otherAnimals"
	salience 20
    when
		(or Person(otherAnimals == "undefined" && allergy=="nie" && familyAllergy=="nie")
		     Person(otherAnimals == "undefined" && allergy=="nie" && family=="nie"))
    then
    	MainWindow.setQuestion("otherAnimals");
end

rule "otherAnimalsSpecific"
	salience 20
    when
		Person(otherAnimals == "tak")
		Pet(otherAnimalsFriendliness == "undefined")
    then
    	MainWindow.setQuestion("otherAnimalsSpecific");
end

rule "cost"
	salience 21
	when 
		Pet(cost=="undefined")
		Person(family!="undefined")
	then
	    	MainWindow.setQuestion("cost");
end 

rule "lifeExpectancy"
	salience 22
	when 
		Pet(lifeExpectancy=="undefined")
		Person(family!="undefined")
	then
	    	MainWindow.setQuestion("lifeExpectancy");
end 

rule "animalTraits"
	salience 22
	when 
		Pet(personality=="undefined")
		Person(family!="undefined")
	then
	    	MainWindow.setQuestion("animalTraits");
end 

rule "activity"
	salience 24
	when
		Person(activity == "undefined")
		Pet(timeRequirements != "poniżej 0.5")
		Pet(lifeExpectancy != "poniżej 7")
	then
		MainWindow.setQuestion("activity");
end 

rule "home"
	salience 25
	when
		Person(homeType == "undefined")
		Pet(timeRequirements != "poniżej 0.5")
	then
	    	MainWindow.setQuestion("home");
end

rule "homeSurroundingsHouse"
	salience 26
	when
		Person (homeType=="w domu jednorodzinnym" && allergy=="nie" && familyAllergy!="tak")
	then
		    	MainWindow.setQuestion("homeSurroundingsHouse");
end

rule "homeSurroundingsFlat"
	salience 26
	when
		Person (homeType=="w mieszkaniu")
	then
		    	MainWindow.setQuestion("homeSurroundingsFlat");
end */
	

