package com.petpicker

import java.util.ArrayList;
  import java.io.BufferedReader;
  import java.io.IOException;
  import java.io.InputStreamReader;

rule "age"
	salience 101
    when
    	not (exists (Property(type=="age")))
    then
    	Property age = MainWindow.setQuestion("age");
    	insert (new Property(age.getType(), age.getValue()));
end

rule "allergyGeneral"
	salience 100
    when
        not (exists (Property(type=="allergyGeneral")))
    then
        Property allergy = MainWindow.setQuestion("allergy");
        insert (new Property(allergy.getType(), allergy.getValue()));
end


rule "allergySpecificI"
	salience 100
	when
	    not (exists (Property(type=="allergyType")))
		Property(type=="allergy" && value=="tak")
	then
		Property allergyType = MainWindow.setQuestion("allergyType");
		insert (new Property(allergyType.getType(), allergyType.getValue()));
end

rule "family"
    salience 99
    when
        not (exists (Property(type=="family")))
    then
    	Property family = MainWindow.setQuestion("family");
    	insert (new Property(family.getType(), family.getValue()));
end

rule "childSubstitute"
	salience 99
    when
      	not (exists (Property(type=="childSubstitute")))  
		(or (Property(type=="family" && value=="nie"))
			(Property(type=="children" && value=="nie"))
		
		)
    then
    	Property childSubstitute = MainWindow.setQuestion("childSubstitute");
    	insert (new Property(childSubstitute.getType(), childSubstitute.getValue()));
end

rule "allergySpecificII"
    salience 100
	when
	    not (exists (Property(type=="familyAllergyType"))) 
		Property(type=="familyAllergy" && value=="tak")
	then
		Property allergySpecific = MainWindow.setQuestion("allergySpecificII");
		insert (new Property(allergySpecific.getType(), allergySpecific.getValue()));
end

rule "familyAllergy"
    salience 100
    when
        not (exists (Property(type=="familyAllergy"))) 
		Property(type=="family" && value=="tak")
		Property(type=="furPossible" && value == "tak")
    then
    	Property familyAllergy = MainWindow.setQuestion("familyAllergy");
    	insert (new Property(familyAllergy.getType(), familyAllergy.getValue()));
end

rule "children"
	salience 99
    when
    	not (exists (Property(type=="children"))) 
		Property(type=="family" && value=="tak")
    then
    	Property children = MainWindow.setQuestion( "children");
    	insert (new Property(children.getType(), children.getValue()));
end

rule "childrenAge"
	salience 99
    when
        not (exists (Property(type=="childrenAge"))) 
		Property(type=="children" && value=="tak")
    then
    	Property childrenAge = MainWindow.setQuestion("childrenAge");
    	insert (new Property(childrenAge.getType(), childrenAge.getValue()));
end

rule "timeRequirements"
	salience 80
    when
        not (exists (Property(type=="timeRequirements")))
        Property(type=="childSubstitute" && value=="nie") 
    then
    	Property timeReq = MainWindow.setQuestion("timeRequirements");
		insert (new Property(timeReq.getType(), timeReq.getValue()));
end

rule "cost"
	salience 80
	when
			not (exists (Property(type=="cost")))
			Property(type=="childSubstitute" && value=="nie") 
	then
	    	Property cost = MainWindow.setQuestion("cost");
	    	insert (new Property(cost.getType(), cost.getValue()));
end 

rule "lifeExpectancy"
	salience 80
	when
			not (exists (Property(type=="lifeExpectancy"))) 
	then
	    	Property le = MainWindow.setQuestion("lifeExpectancy");
	    	insert (new Property(le.getType(), le.getValue()));
end 

rule "animalTraits"
	salience 80
	when
	 		not (exists (Property(type=="personality")))
	 		Property(type=="childSubstitute" && value=="nie") 
	then
	    	Property traits = MainWindow.setQuestion("animalTraits");
	    	insert (new Property(traits.getType(), traits.getValue()));
end 

rule "timeAtHome"
	salience 80
    when
        not (exists (Property(type=="timeAtHome"))) 
		Property(type=="family" && value=="nie")
		not (exists (Property(type=="childSubstitute" && value=="tak")))
    then
    	Property time = MainWindow.setQuestion("timeAtHome");
    	insert (new Property(time.getType(), time.getValue()));
end

rule "otherAnimals"
    when
		(or (Property (type=="dogPossible" && value=="tak"))
			(Property (type=="catPossible" && value=="tak"))
		)
		not (exists (Property(type=="otherAnimals")))
    then
    	Property other = MainWindow.setQuestion("otherAnimals");
    	insert (new Property(other.getType(), other.getValue()));
end

rule "otherAnimalsSpecific"
    when
        not (exists (Property(type=="otherAnimalsFriendliness"))) 
		Property(type=="otherAnimals" && value=="tak")
    then
    	Property other2 = MainWindow.setQuestion("otherAnimalsSpecific");
    	insert (new Property(other2.getType(), other2.getValue()));
end

rule "activity"
	when
		not (exists (Property(type=="activity"))) 
		Property(type=="dogPossible" && value=="tak")
		not (exists (Property(type=="age" && value=="powyżej 60")))
	then
		Property activity = MainWindow.setQuestion("activity");
		insert (new Property(activity.getType(), activity.getValue()));
end 

rule "home"
	when
		not (exists (Property(type=="homeType"))) 
		Property(type=="dogPossible" && value=="tak")
	then
	    Property home = MainWindow.setQuestion("home");
	    insert (new Property(home.getType(), home.getValue()));	
end

rule "homeSurroundingsHouse"
	when
		not (exists (Property(type=="homeSurroundingsHouse")))
		exists (Property(type=="homeType"))
		Property(type=="homeType" && value=="w domu jednorodzinnym")
	then
		Property hs = MainWindow.setQuestion("homeSurroundingsHouse");
		insert (new Property(hs.getType(), hs.getValue()));
end

rule "homeSurroundingsFlat"
	when
		not (exists (Property(type=="homeSurroundingsFlat")))
		exists (Property(type=="homeType"))
		Property(type=="homeType" && value=="w mieszkaniu")
	then
		Property hs = MainWindow.setQuestion("homeSurroundingsFlat");
		insert (new Property(hs.getType(), hs.getValue()));
end 

rule "inteligence"
	when
		not (exists (Property(type=="inteligence")))
	then
		Property inteligence = MainWindow.setQuestion("inteligence");
		insert (new Property(inteligence.getType(), inteligence.getValue()));
end	

rule "space"
	when
		not (exists (Property(type=="space")))
		exists (Property(type=="homeType"))
		Property(type=="homeType" && value=="w mieszkaniu")
	then
		Property space = MainWindow.setQuestion("space");
		insert (new Property(space.getType(), space.getValue()));
end	

rule "lifestyle"
	when
		not (exists (Property(type=="lifestyle")))
	then
		Property property = MainWindow.setQuestion("lifestyle");
		insert (new Property(property.getType(), property.getValue()));
end

rule "defense"
	when
		not (exists (Property(type=="defense")))	
		Property(type=="dogPossible" && value=="tak")
		Property(type=="homeType" && value=="w domu jednorodzinnym")
		not (exists (Property(type=="childSubstitute" && value=="tak")))
	then
		Property property = MainWindow.setQuestion("defense");
		insert (new Property(property.getType(), property.getValue()));
end

rule "hunting"
	when
		not (exists (Property(type=="hunting")))	
		Property(type=="dogPossible" && value=="tak")
		not (exists (Property(type=="childSubstitute" && value=="tak")))
	then
		Property property = MainWindow.setQuestion("hunting");
		insert (new Property(property.getType(), property.getValue()));
end

rule "apperance"
	when
		not (exists (Property(type=="appearance")))
		Property(type=="dogPossible" && value=="nie")	
	then
		Property property = MainWindow.setQuestion("appearance");
		insert (new Property(property.getType(), property.getValue()));
end

rule "odour"
	when
		not (exists (Property(type=="odour")))
		Property(type=="dogPossible" && value=="nie")
		Property(type=="catPossible" && value=="nie")
	then
		Property property = MainWindow.setQuestion("odour");
		insert (new Property(property.getType(), property.getValue()));
end

rule "animalActivity"
	when
		not (exists (Property(type=="animalActivity")))	
	then
		Property property = MainWindow.setQuestion("animalActivity");
		insert (new Property(property.getType(), property.getValue()));
end

rule "fur"
	when
		not (exists (Property(type=="fur")))	
		(or	(Property(type=="dogPossible" && value=="tak"))
			(Property(type=="catPossible" && value=="tak"))
		)
	then
		Property property = MainWindow.setQuestion("fur");
		insert (new Property(property.getType(), property.getValue()));
end

rule "dogPossible"
 	salience 100
 	when
 		not (exists( (Property(type=="allergyType" && value=="na psy"))))
 		not (exists( (Property(type=="familyAllergyType" && value=="na psy"))))
 	then
 		insertLogical (new Property("dogPossible", "tak"));
 		System.out.println("dog possible"); 	
 end
 
  rule "catPossible"
  	salience 100
 	when
 		not (exists( (Property(type=="allergyType" && value=="na koty"))))
 		not (exists( (Property(type=="familyAllergyType" && value=="na koty"))))
 	then
 		insertLogical (new Property("catPossible", "tak"));
 		System.out.println("cat possible"); 	
 end
 
   rule "furPossible"
    salience 100
 	when
 		not (exists( (Property(type=="allergyType" && value=="na większość zwierząt z sierścią"))))
 		not (exists( (Property(type=="familyAllergyType" && value=="na większość zwierząt z sierścią"))))
 	then
 		insertLogical (new Property("furPossible", "tak"));
 		System.out.println("fur possible"); 	
 end
 
rule "excludeDog"
	salience 80
	when
		dog: Property(type=="dogPossible" && value=="tak")
		(or	(Property(type=="timeRequirements" && value=="poniżej 0.5"))
			(Property(type=="cost" && value=="jak najniższy"))
			(Property(type=="lifeExpectancy" && value=="poniżej 12"))
			(Property(type=="timeAtHome" && value=="tak"))
			(Property(type=="space" && value=="mało"))
			(Property(type=="lifestyle" && value=="w nocy"))
		)  
	then
		modify (dog) {setValue("nie")};
end

rule "excludeCat"
	salience 80
	when
		cat: Property(type=="catPossible" && value=="tak")
		(or	(Property(type=="timeRequirements" && value=="poniżej 0.5"))
			(Property(type=="cost" && value=="jak najniższy"))
			(Property(type=="lifeExpectancy" && value=="poniżej 12"))
		)  
	then
		modify (cat) {setValue("nie")};
end 	 		
