package com.petpicker
 
 rule "dogPossible"
 	salience 100
 	when
 		not (exists( (Property(type=="allergyType" && value=="na psy"))))
 		not (exists( (Property(type=="familyAllergyType" && value=="na psy"))))
 	then
 		insertLogical (new Property("dogPossible", "tak"));
 		System.out.println("dog possible"); 	
 end
 
  rule "catPossible"
  	salience 100
 	when
 		not (exists( (Property(type=="allergyType" && value=="na koty"))))
 		not (exists( (Property(type=="familyAllergyType" && value=="na koty"))))
 	then
 		insertLogical (new Property("catPossible", "tak"));
 		System.out.println("cat possible"); 	
 end
 
   rule "furPossible"
    salience 100
 	when
 		not (exists( (Property(type=="allergyType" && value=="na większość zwierząt z sierścią"))))
 		not (exists( (Property(type=="familyAllergyType" && value=="na większość zwierząt z sierścią"))))
 	then
 		insertLogical (new Property("furPossible", "tak"));
 		System.out.println("fur possible"); 	
 end
 





